[theme]
base = "light"
primaryColor = "#2D6A4F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"

[client]
toolbarMode="minimal"

[browser]
gatherUsageStats = false